def generate_render_test(payload):
    lines = [
        "import bpy",
        "",
        "# --- CLEAN SCENE ---",
        "bpy.ops.object.select_all(action='SELECT')",
        "bpy.ops.object.delete()",
        "",
        "# --- BUDDY VOXEL BODY ---",
        "def add_cube(x, y, z, size):",
        "    bpy.ops.mesh.primitive_cube_add(size=size, location=(x, y, z))",
        "",
        "add_cube(0, 0, 0, 1.0)",
        "add_cube(1, 0, 0, 1.0)",
        "add_cube(0, 1, 0, 1.0)",
        "add_cube(1, 1, 0, 1.0)",
        "add_cube(0, 0, 1, 1.0)",
        "add_cube(1, 0, 1, 1.0)",
        "add_cube(0, 1, 1, 1.0)",
        "add_cube(1, 1, 1, 1.0)",
        "add_cube(0.5, 0.5, 2, 1.0)",
        "",
        "# --- MATERIAL ---",
        "mat = bpy.data.materials.new(name='BuddyFur')",
        "mat.use_nodes = True",
        "bsdf = mat.node_tree.nodes.get('Principled BSDF')",
        "bsdf.inputs['Base Color'].default_value = (0.8, 0.5, 0.3, 1.0)",
        "",
        "for obj in bpy.context.selected_objects:",
        "    if obj.data.materials:",
        "        obj.data.materials[0] = mat",
        "    else:",
        "        obj.data.materials.append(mat)",
        "",
        "# --- ARMATURE ---",
        "arm_data = bpy.data.armatures.new('BuddyArmature')",
        "arm_obj = bpy.data.objects.new('BuddyArmature', arm_data)",
        "bpy.context.collection.objects.link(arm_obj)",
        "bpy.context.view_layer.objects.active = arm_obj",
        "bpy.ops.object.mode_set(mode='EDIT')",
        "",
        "root = arm_data.edit_bones.new('root')",
        "root.head = (0.5, 0.5, 0)",
        "root.tail = (0.5, 0.5, 1)",
        "",
        "spine = arm_data.edit_bones.new('spine')",
        "spine.head = (0.5, 0.5, 1)",
        "spine.tail = (0.5, 0.5, 2)",
        "",
        "head = arm_data.edit_bones.new('head')",
        "head.head = (0.5, 0.5, 2)",
        "head.tail = (0.5, 0.5, 3)",
        "",
        "left_leg = arm_data.edit_bones.new('left_leg')",
        "left_leg.head = (0.2, 0.5, 0)",
        "left_leg.tail = (0.2, 0.5, -1)",
        "",
        "right_leg = arm_data.edit_bones.new('right_leg')",
        "right_leg.head = (0.8, 0.5, 0)",
        "right_leg.tail = (0.8, 0.5, -1)",
        "",
        "bpy.ops.object.mode_set(mode='OBJECT')",
        "",
        "# --- WALK CYCLE ---",
        "obj = arm_obj",
        "obj.animation_data_create()",
        "action = bpy.data.actions.new(name='BuddyWalkSoft')",
        "obj.animation_data.action = action",
        "",
        "def kf_loc(bone, frame, loc):",
        "    pb = obj.pose.bones[bone]",
        "    pb.location = loc",
        "    pb.keyframe_insert(data_path='location', frame=frame)",
        "",
        "def kf_rot(bone, frame, rot):",
        "    pb = obj.pose.bones[bone]",
        "    pb.rotation_euler = rot",
        "    pb.keyframe_insert(data_path='rotation_euler', frame=frame)",
        "",
        "# root bounce",
        "kf_loc('root', 1,  (0,0,0.00))",
        "kf_loc('root', 6,  (0,0,0.05))",
        "kf_loc('root', 12, (0,0,0.00))",
        "kf_loc('root', 18, (0,0,-0.03))",
        "kf_loc('root', 24, (0,0,0.00))",
        "",
        "# spine lean",
        "kf_rot('spine', 1,  (0.05,0,0))",
        "kf_rot('spine', 12, (0.10,0,0))",
        "kf_rot('spine', 24, (0.05,0,0))",
        "",
        "# head sway",
        "kf_rot('head', 1,  (0,0,0))",
        "kf_rot('head', 6,  (0,0.10,0))",
        "kf_rot('head', 12, (0,0,0))",
        "kf_rot('head', 18, (0,-0.10,0))",
        "kf_rot('head', 24, (0,0,0))",
        "",
        "# legs",
        "kf_rot('left_leg', 1,  (0.20,0,0))",
        "kf_rot('left_leg', 12, (-0.20,0,0))",
        "kf_rot('left_leg', 24, (0.20,0,0))",
        "",
        "kf_rot('right_leg', 1,  (-0.20,0,0))",
        "kf_rot('right_leg', 12, (0.20,0,0))",
        "kf_rot('right_leg', 24, (-0.20,0,0))",
        "",
        "# --- CAMERA ---",
        "cam_data = bpy.data.cameras.new('RenderCam')",
        "cam_obj = bpy.data.objects.new('RenderCam', cam_data)",
        "bpy.context.collection.objects.link(cam_obj)",
        "cam_obj.location = (4, -6, 4)",
        "cam_obj.rotation_euler = (1.1, 0, 0.6)",
        "bpy.context.scene.camera = cam_obj",
        "",
        "# --- LIGHT ---",
        "light_data = bpy.data.lights.new(name='RenderLight', type='POINT')",
        "light_data.energy = 1500",
        "light_obj = bpy.data.objects.new('RenderLight', light_data)",
        "bpy.context.collection.objects.link(light_obj)",
        "light_obj.location = (5, -5, 6)",
        "",
        "# --- RENDER SETTINGS ---",
        "bpy.context.scene.render.engine = 'BLENDER_EEVEE'",
        "bpy.context.scene.render.image_settings.file_format = 'PNG'",
        "bpy.context.scene.render.filepath = '//buddy_render.png'",
        "bpy.context.scene.frame_set(1)",
        "",
        "# --- RENDER FRAME ---",
        "bpy.ops.render.render(write_still=True)",
    ]

    return { "script": "\n".join(lines) }
